from typing import Any, Dict, List
from copy import deepcopy


class MessageHistory:
    """ Class for tracking the history of messages generated by an agent """

    def __init__(self, messages: List[Dict[str, Any]]=[]):
        self.messages = messages

    def add_message(self, message: Dict[str, Any]):
        self.messages.append(message)

    def add_messages(self, messages: List[Dict[str, Any]]):
        for message in messages:
            self.add_message(message)

    def get_messages(self):
        return self.messages

    def clone(self):
        cloned_messages = deepcopy(self.messages)
        return MessageHistory(messages=cloned_messages)

    def reset(self):
        self.messages = []
