from typing import Any, Dict, List
from copy import deepcopy

from ..llms import LLM
from ..config import get_config


class MessageHistory:
    """ Class for tracking the history of messages generated by an agent """


    def __init__(self):
        self.messages = []
        self.config = get_config()
        self.context_compaction_params = self.config.context_compaction_params


    def add_message(self, round_num: int, message: Dict[str, Any]):
        if round_num >= len(self.messages):
            self.messages.append([])

        self.messages[round_num].append(message)

    def add_messages(self, round_num: int, messages: List[Dict[str, Any]]):
        for message in messages:
            self.add_message(round_num, message)

    def get_messages(self):
        return sum(self.messages, [])

    def clone(self):
        cloned_messages = MessageHistory()
        cloned_messages.messages = deepcopy(self.messages)
        return cloned_messages

    def reset(self):
        self.messages = []

    def is_compactaion_required(self, token_utilization: int, llm: LLM) -> bool:
        llm_context_window_size = llm.get_context_window_size()
        token_utilization_percentage = token_utilization / llm_context_window_size
        if token_utilization_percentage > self.context_compaction_params['trigger_llm_context_utilization_threshold']:
            return True
        return False

